// SPDX-License-Identifier: GPL-3.0
// This file is auto-generated by snarkjs after running: make setup
// Run `make setup` to regenerate with the actual trusted-setup verification key.
// The placeholder constants below are NOT valid — the contract will revert until regenerated.
pragma solidity ^0.8.19;

contract Groth16Verifier {
    // BN254 scalar field size
    uint256 constant r = 21888242871839275222246405745257275088548364400416034343698204186575808495617;
    // BN254 base field size
    uint256 constant q = 21888242871839275222246405745257275088696311157297823662689037894645226208583;

    // ── Verification Key ────────────────────────────────────────────────────────
    // PLACEHOLDER — regenerated by `snarkjs zkey export solidityverifier`
    uint256 constant alphax  = 0;
    uint256 constant alphay  = 0;
    uint256 constant betax1  = 0;
    uint256 constant betax2  = 0;
    uint256 constant betay1  = 0;
    uint256 constant betay2  = 0;
    uint256 constant gammax1 = 0;
    uint256 constant gammax2 = 0;
    uint256 constant gammay1 = 0;
    uint256 constant gammay2 = 0;
    uint256 constant deltax1 = 0;
    uint256 constant deltax2 = 0;
    uint256 constant deltay1 = 0;
    uint256 constant deltay2 = 0;

    // IC[0..3]: one entry per public signal + 1
    uint256 constant IC0x = 0;
    uint256 constant IC0y = 0;
    uint256 constant IC1x = 0;
    uint256 constant IC1y = 0;
    uint256 constant IC2x = 0;
    uint256 constant IC2y = 0;
    uint256 constant IC3x = 0;
    uint256 constant IC3y = 0;

    // ── Pairing helpers ─────────────────────────────────────────────────────────

    function _negate(uint256 x, uint256 y) internal pure returns (uint256, uint256) {
        if (x == 0 && y == 0) return (0, 0);
        return (x, q - (y % q));
    }

    function _addition(
        uint256 ax, uint256 ay,
        uint256 bx, uint256 by
    ) internal view returns (uint256 cx, uint256 cy) {
        uint256[4] memory input = [ax, ay, bx, by];
        bool ok;
        assembly {
            ok := staticcall(gas(), 6, input, 0x80, cx, 0x40)
        }
        require(ok, "pairing-add-failed");
    }

    function _mulScalar(
        uint256 px, uint256 py, uint256 s
    ) internal view returns (uint256 qx, uint256 qy) {
        uint256[3] memory input = [px, py, s];
        bool ok;
        assembly {
            ok := staticcall(gas(), 7, input, 0x60, qx, 0x40)
        }
        require(ok, "pairing-mul-failed");
    }

    function _pairingCheck(uint256[24] memory input) internal view returns (bool) {
        uint256[1] memory out;
        bool ok;
        assembly {
            ok := staticcall(gas(), 8, input, 0x300, out, 0x20)
        }
        require(ok, "pairing-check-failed");
        return out[0] == 1;
    }

    // ── Public entry point ───────────────────────────────────────────────────────

    /// @param _pA  proof.pi_a  [x, y]
    /// @param _pB  proof.pi_b  [[x2,x1],[y2,y1]]
    /// @param _pC  proof.pi_c  [x, y]
    /// @param _pubSignals [merkleRoot, taskHashCommitment, nullifierHash]
    function verifyProof(
        uint256[2]    calldata _pA,
        uint256[2][2] calldata _pB,
        uint256[2]    calldata _pC,
        uint256[3]    calldata _pubSignals
    ) public view returns (bool) {
        // Range-check public signals
        require(_pubSignals[0] < r, "pubSignal[0] out of range");
        require(_pubSignals[1] < r, "pubSignal[1] out of range");
        require(_pubSignals[2] < r, "pubSignal[2] out of range");

        // Compute linear combination of IC points with public signals
        (uint256 vkx, uint256 vky) = (IC0x, IC0y);
        (uint256 s1x, uint256 s1y) = _mulScalar(IC1x, IC1y, _pubSignals[0]);
        (uint256 s2x, uint256 s2y) = _mulScalar(IC2x, IC2y, _pubSignals[1]);
        (uint256 s3x, uint256 s3y) = _mulScalar(IC3x, IC3y, _pubSignals[2]);
        (vkx, vky) = _addition(vkx, vky, s1x, s1y);
        (vkx, vky) = _addition(vkx, vky, s2x, s2y);
        (vkx, vky) = _addition(vkx, vky, s3x, s3y);

        (uint256 pAny, uint256 pAny2) = _negate(_pA[0], _pA[1]);

        uint256[24] memory pairingInput = [
            pAny,       pAny2,
            _pB[0][1],  _pB[0][0],  _pB[1][1],  _pB[1][0],
            vkx,        vky,
            gammax1,    gammax2,     gammay1,     gammay2,
            _pC[0],     _pC[1],
            deltax1,    deltax2,     deltay1,     deltay2,
            alphax,     alphay,
            betax1,     betax2,      betay1,      betay2
        ];

        return _pairingCheck(pairingInput);
    }
}
